FROM python:3.8

WORKDIR /patamaen
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install gunicorn
COPY . .

EXPOSE 8000
CMD python manage.py collectstatic --noinput --clear && \
  gunicorn patamaen.wsgi -b 0.0.0.0:8000
